run_tests: # any_name_possible_for_job
  image: python:3.9-slim-buster # need to override
  before_script:
    - apt-get update && apt-get install make # need to have make utility
  script:
    - make test

build_image: # any_name_possible_for_job
  image: docker:20.10.16 # docker in docker image to run docker client
  services:
    - docker:20.10.16-dind # service container for deamon
  variables: # Job Variables
    DOCKER_TLS_CERTDIR: "/cert" # need to job-server containers communication
    IMAGE_NAME: dockeruser/docker-image
    IMAGE_TAG: docker-image-tag-1.0
  before_script:
    - docker login -u $REG_USER -p $REG_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
