run_tests: # any_name_possible_for_job
  image: python:3.9-slim-buster # needs to override
  before_script:
    - apt-get update && apt-get install make # needs to have make utility
  script:
    - make test

build_image: # 
  image: docker:20.10.16 # docker in docker image to run docker client
  services:
    - docker:20.10.16-dind # service container for deamon
  variables: # Job Variables
    DOCKER_TLS_CERTDIR: "/cert" # need to job-server containers communication
  script:
    #                Dockerfile in repository root   
    # - docker build .
    - docker build -t dockeruser/docker-image:docker-image-tag-1.0 .
